version: 2.1

executors:
  python_executor:
    resource_class: medium
    docker:
      - image: circleci/python:3.7

jobs:
  build_and_push:
    executor: python_executor
    steps:
      - checkout
      - run:
          name: "Build and Push"
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t mqarty/docker-firebase:$TAG -t mqarty/docker-firebase:latest .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push mqarty/docker-firebase:$TAG
            docker push mqarty/docker-firebase:latest

workflows:
  version: 2
  build_and_push_image:
    jobs:
      - build_and_push:
          context: Docker
