version: 2
jobs:
  build_and_push:
    docker:
      - image: docker:18.04.0-ce-rc2
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Build and Push"
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t mqarty/docker-firebase:$TAG -t mqarty/docker-firebase:latest .
            docker login -u $DOCKER_USER --password-stdin $DOCKER_PASS
            docker push mqarty/docker-firebase:latest mqarty/docker-firebase:$TAG
workflows:
  version: 2
  build_and_push_image:
    jobs:
      - build_and_push:
          context: Docker
